import React from "react";

export default function AlertsLogView({ ctx }) {
  const {
    view,
    setViewRaw,
    prjs,
    setPrjs,
    selId,
    setSelIdRaw,
    expS,
    setExpS,
    showNew,
    setShowNew,
    prjSearch,
    setPrjSearch,
    priFilt,
    setPriFilt,
    newP,
    setNewP,
    clk,
    setClk,
    stF,
    setStF,
    stS,
    setStS,
    stD,
    setStD,
    editing,
    setEditing,
    editSnap,
    setEditSnap,
    salesTab,
    setSalesTab,
    estView,
    setEstView,
    estStoneId,
    setEstStoneId,
    estDims,
    setEstDims,
    estCx,
    setEstCx,
    estQty,
    setEstQty,
    estQ,
    setEstQ,
    expEst,
    setExpEst,
    estSearch,
    setEstSearch,
    quoteFilter,
    setQuoteFilter,
    quoteSortBy,
    setQuoteSortBy,
    expAlert,
    setExpAlert,
    alertLog,
    setAlertLog,
    orderModal,
    setOrderModal,
    orderPrj,
    setOrderPrj,
    orderQty,
    setOrderQty,
    orderDims,
    setOrderDims,
    orderNotes,
    setOrderNotes,
    rfqModal,
    setRfqModal,
    rfqPrj,
    setRfqPrj,
    rfqQty,
    setRfqQty,
    rfqDims,
    setRfqDims,
    rfqNotes,
    setRfqNotes,
    rfqTimeline,
    setRfqTimeline,
    rfqEditId,
    setRfqEditId,
    rfqEditNote,
    setRfqEditNote,
    stDbTab,
    setStDbTab,
    orderSearch,
    setOrderSearch,
    editingQuoteId,
    setEditingQuoteId,
    showResolved,
    setShowResolved,
    finAiOpen,
    setFinAiOpen,
    finTab,
    setFinTab,
    mktTab,
    setMktTab,
    robotTab,
    setRobotTab,
    selRobot,
    setSelRobot,
    sc,
    setSc,
    designRecs,
    setDesignRecs,
    sourceRecs,
    setSourceRecs,
    tpGenState,
    setTpGenState,
    tpGenTime,
    setTpGenTime,
    tpProgress,
    setTpProgress,
    tpStatus,
    setTpStatus,
    invDetail,
    setInvDetail,
    invBlocks,
    setInvBlocks,
    allocPrj,
    setAllocPrj,
    cpName,
    setCpName,
    cpEmail,
    setCpEmail,
    cpType,
    setCpType,
    cpDims,
    setCpDims,
    cpStone,
    setCpStone,
    cpBudget,
    setCpBudget,
    cpNotes,
    setCpNotes,
    cpSubmitted,
    setCpSubmitted,
    cpFiles,
    setCpFiles,
    macroTF,
    setMacroTF,
    macroTab,
    setMacroTab,
    macroAI,
    setMacroAI,
    mcPanelOpen,
    setMcPanelOpen,
    mcPanelWidth,
    setMcPanelWidth,
    mcPanelTab,
    setMcPanelTab,
    mcTab,
    setMcTab,
    mcExp,
    setMcExp,
    mcFilt,
    setMcFilt,
    mcDone,
    setMcDone,
    lFilt,
    setLFilt,
    lStatus,
    setLStatus,
    lExp,
    setLExp,
    gSearch,
    setGSearch,
    gSearchOpen,
    setGSearchOpen,
    gSearchFocused,
    setGSearchFocused,
    sideOpen,
    setSideOpen,
    sidebarPinned,
    setSidebarPinned,
    estFiles,
    setEstFiles,
    estAiRefresh,
    setEstAiRefresh,
    stoneDetail,
    setStoneDetail,
    prjRfqLog,
    setPrjRfqLog,
    dbRefreshing,
    setDbRefreshing,
    stDbSearch,
    setStDbSearch,
    alertSearch,
    setAlertSearch,
    estEmailTo,
    setEstEmailTo,
    estClientName,
    setEstClientName,
    estProjectName,
    setEstProjectName,
    estAgentCtx,
    setEstAgentCtx,
    estMargin,
    setEstMargin,
    lossConfirm,
    setLossConfirm,
    quoteApplied,
    setQuoteApplied,
    estShopEmail,
    setEstShopEmail,
    estActionLog,
    setEstActionLog,
    showEstAction,
    setShowEstAction,
    finOverrides,
    setFinOverrides,
    finEditing,
    setFinEditing,
    finScenario,
    setFinScenario,
    finScenarioAdj,
    setFinScenarioAdj,
    alertFilt,
    setAlertFilt,
    leads,
    setLeads,
    selLead,
    setSelLead,
    leadSearch,
    setLeadSearch,
    leadStageFilt,
    setLeadStageFilt,
    pipeQuickFilt,
    setPipeQuickFilt,
    prjTabFilt,
    setPrjTabFilt,
    contactSearch,
    setContactSearch_,
    selContact,
    setSelContact,
    selContactEst,
    setSelContactEst,
    selSupplier,
    setSelSupplier,
    showNewLead,
    setShowNewLead,
    newLead,
    setNewLead,
    capWeek,
    setCapWeek,
    capView,
    setCapView,
    capTab,
    setCapTab,
    capSelSup,
    setCapSelSup,
    capSelClient,
    setCapSelClient,
    tblSort,
    setTblSort,
    capSelPerson,
    setCapSelPerson,
    selDay,
    setSelDay,
    selWeekCF,
    setSelWeekCF,
    cfRange,
    setCfRange,
    revRange,
    setRevRange,
    plRange,
    setPlRange,
    estRobotRate,
    setEstRobotRate,
    estHandRate,
    setEstHandRate,
    estOverhead,
    setEstOverhead,
    estProfit,
    setEstProfit,
    estDist,
    setEstDist,
    estShipFactor,
    setEstShipFactor,
    estQuality,
    setEstQuality,
    newMenuOpen,
    setNewMenuOpen,
    viewTab,
    setViewTab,
    mcOrigin,
    setMcOrigin,
    M,
    S,
    D,
    G,
    CB,
    BD,
    $,
    PC,
    TT,
    PRI,
    STAT_C,
    FC,
    CC,
    ROLES_C,
    stonePrice,
    genInv,
    now,
    ts,
    AsOf,
    STAGES,
    STONE_DB,
    ROBOTS,
    CARVERS,
    INIT_PRJS,
    mkSD,
    INIT_EST_QUEUE,
    EST_STEPS,
    Dot,
    Lbl,
    Badge,
    Btn,
    KPI,
    NAV,
    VIEW_CFG,
    ROUTE_MAP,
    nav,
    finAdj,
    aR,
  } = ctx;

  return (<>
      {view==="alerts"&&(()=>{
        const ALERTS=[
          // ── ALERTS ──
          {id:"A1",t:"14:22",ty:"alert",m:"KUKA Epsilon — spindle temp anomaly detected. Automated maintenance protocol initiated.",det:"Spindle temperature reached 87°C (threshold: 75°C). Auto-shutdown triggered at 14:21. Cooling cycle started. Last maintenance: Jan 28, 2026. Spindle runtime: 342h since service. Recommended action: swap spindle assembly if temp persists after cooldown.",s:"Robot Monitor",sev:"high",owner:"Shop Floor"},
          {id:"A11",t:"Yesterday 11:00",ty:"alert",m:"Block BLK-2026-0004 (Calacatta Gold, Stripe Logo) — hairline vein near edge.",det:"QA inspection found 12cm hairline vein 3mm from block edge. Risk: LOW — carve zone is center-block. Recommend: proceed with milling, monitor during roughing. Fallback block BLK-2026-0004B available.",s:"Quality Assurance",sev:"medium",owner:"QA"},
          {id:"A20",t:"Yesterday 09:10",ty:"alert",m:"KUKA Alpha — tool bit #3 worn beyond threshold. Swap required before next pass.",det:"Bit wear sensor reading 94% degradation. 6mm ball-nose, installed Feb 18. Estimated remaining life: <30 min milling. Replacement bits in cabinet R3. Swap takes ~8 min. Next pass starts 10:00.",s:"Robot Monitor",sev:"medium",owner:"Shop Floor"},
          {id:"A21",t:"Feb 18, 15:30",ty:"alert",m:"PRJ-018 (Lion Pair) — stone sourcing still unconfirmed. Fabrication blocked.",det:"Estremoz White blocks still showing 'Not ordered' status. Fabrication scheduled to begin Mar 3. Order must be placed by Feb 25 for 3-week lead time. Supplier: Alentejo Marble SA. Contact: orders@alentejo-marble.com.",s:"Supply Chain",sev:"high",a:true,owner:"Purchasing"},
          // ── DECISIONS ──
          {id:"A5",t:"10:05",ty:"decision",m:"NEH National Garden — maquette review extended to March 1. Notify 3 artists.",det:"NEH committee requested 2-week extension. Artists under review: Vinnie Bagwell, Preston Jackson, Alison Saar. Must send formal timeline update to each studio. Delays stone ordering ~2 weeks.",s:"Project Management",sev:"high",a:true,owner:"Micah S."},
          {id:"A9",t:"Yesterday 16:40",ty:"decision",m:"Benedictine — Bootsma requesting accelerated timeline. Evaluate 2nd robot.",det:"Erik Bootsma requesting completion by April 15 (6 weeks early). Options: (1) Add KUKA Gamma — reduces timeline ~4 weeks, requires toolpath duplication. (2) Overtime shifts — ~2 week gain. (3) Negotiate partial delivery of 8 by April.",s:"Project Management",sev:"high",a:true,owner:"Micah S."},
          {id:"A22",t:"Feb 17, 11:00",ty:"decision",m:"Gensler Brooklyn — quote revision requested. Deadline March 15. Respond within 7 days.",det:"Isabelle Morel (Gensler) requesting 8% price reduction on $280k quote. Current margin: 18%. Options: (1) Hold firm — 78% historical win rate at 18%. (2) Offer 4% reduction to $268k — margin 14%. (3) Add value: expedited timeline instead of price cut.",s:"Sales",sev:"high",a:true,owner:"Sales"},
          {id:"A23",t:"Feb 16, 14:00",ty:"decision",m:"Soho House invoice 67 days overdue — escalation path needed.",det:"Thomas Aquino unresponsive since Feb 10. Invoice: $21,000 balance. Options: (1) Formal demand letter via counsel. (2) Direct call to Soho House VP. (3) Place project on hold. Relationship at risk but $21k outstanding.",s:"Finance",sev:"high",a:true,owner:"Accounts"},
          // ── FINANCE ──
          {id:"A3",t:"12:10",ty:"finance",m:"Invoice INV-2025-0025 RAMSA — $187,500 wire received. Balance: $187,500.",det:"Payment cleared via JPMorgan wire. Ref: WR-2026-0219. Remaining: $187,500 (Invoice #2 not yet sent). Project margin on track at 15%.",s:"Finance",sev:"info",owner:"Accounts"},
          {id:"A10",t:"Yesterday 14:15",ty:"finance",m:"Monthly burn report: $145k/mo. Runway: 8.2 months.",det:"Feb projection: $145k (staff $89k, facility $28k, materials $18k, equipment $10k). Cash: $1,189k. AR outstanding: $382,500. Expected collections next 30d: ~$230k.",s:"Finance",sev:"medium",owner:"Finance"},
          {id:"A24",t:"Feb 18, 09:00",ty:"finance",m:"Q1 revenue projection revised upward to $892k — 3 new wins in pipeline.",det:"Rosewood Hotels ($145k) moved to verbal. Vornado ($230k) quote accepted. Gensler decision expected March 15. If all close: Q1 projects at $892k vs $720k budget. Margin average: 16.2%.",s:"Finance",sev:"info",owner:"Finance"},
          {id:"A25",t:"Feb 14, 16:00",ty:"finance",m:"New: $57,500 invoice sent to Hudson Yards (Vornado) — deposit on granite capitals.",det:"INV-2026-0005 sent to Ben Okafor. Due Feb 28. Wire instructions included. 50% deposit on $115k project. Stone order contingent on receipt.",s:"Finance",sev:"info",owner:"Accounts"},
          // ── SUPPLY ──
          {id:"A4",t:"11:30",ty:"supply",m:"Estremoz White shipment cleared US customs. Updated ETA: Feb 19.",det:"6 blocks, 4.2 tonnes. Cleared Newark customs 11:28. Freight: Maersk MSKU-7284619. Local delivery via flatbed to Greenpoint. Assigned to PRJ-018 (Lion Pair).",s:"Supply Chain",sev:"info",owner:"Logistics"},
          {id:"A8",t:"08:10",ty:"supply",m:"Indiana Limestone restock quote: $850/ton, 20-ton min. Valid 30 days.",det:"Quote from American Stone Supply (ref: QT-2026-0044). FOB Bedford, IN. Shipping to Greenpoint: ~$1,200 flat. Current inventory: 4.5 tons remaining.",s:"Procurement",sev:"info",owner:"Purchasing"},
          {id:"A26",t:"Feb 17, 13:00",ty:"supply",m:"Red Sea freight surcharge: +$800/container added by Maersk. Affects 2 open orders.",det:"Maersk invoiced surcharge on MSKU-7284619 (Estremoz) and upcoming Carrara shipment. Total additional cost: $1,600. Absorbed in current project budgets. Recommend consolidating PRJ-001 and PRJ-003 into single container next order.",s:"Supply Chain",sev:"medium",owner:"Logistics"},
          {id:"A27",t:"Feb 15, 10:00",ty:"supply",m:"Tuscan Stone Group — Carrara White CD price increase notice. +4.2% from March 1.",det:"Letter received from TSG. Current price: $1,850/t. New price: $1,927/t effective March 1. Affects PRJ-004 (NEH) stone order not yet placed. Pre-order recommendation: 3.5t at current price before Feb 28.",s:"Procurement",sev:"medium",a:true,owner:"Purchasing"},
          // ── MILESTONES ──
          {id:"M1",t:"Today 13:45",ty:"milestone",m:"PRJ-005 (Arsham Eroded Venus) — all 6 milling passes complete. Transferred to HITL.",det:"Total robot time: 49.2h on KUKA Beta. All passes within tolerance. Surface quality: Excellent. Elena S. assigned for hand finishing. Est. hand hours: 28–32h.",s:"Fabrication",sev:"info",owner:"Production"},
          {id:"M2",t:"Today 09:20",ty:"milestone",m:"New inquiry received: Schwarz Architects — Nashville facade, 32 limestone panels, est. $420k.",det:"David M. Schwarz Architects, Nashville mixed-use. Scope: 32 Indiana Limestone panels, 1.2×1.2×0.15m. Budget: $400–500k. Routed to estimation agent. Contact: studio@dmsa.com",s:"Business Dev",sev:"info",owner:"Sales"},
          {id:"M3",t:"Today 08:45",ty:"milestone",m:"RAMSA panel #8 passed QA — within 0.3mm tolerance. Moved to crating.",det:"Dimensional inspection complete. All measurements within spec (±0.5mm). Surface finish: Grade A. No defects. Crate type: Custom wood. Inspector: Marco V.",s:"Quality Assurance",sev:"info",owner:"QA"},
          {id:"M4",t:"Yesterday 17:10",ty:"milestone",m:"PRJ-017 (Stripe Logo) — fabrication started. KUKA Zeta running pass 1 of 3.",det:"2D profile roughing pass started 17:08. Est. total time: 6h. Night run approved, no supervision required. Block confirmed secure in fixture. Tool: 6mm flat endmill.",s:"Fabrication",sev:"info",owner:"Production"},
          {id:"M5",t:"Yesterday 15:00",ty:"milestone",m:"Quote QT-2026-0018 sent to Rosewood Hotels — $145k grand lobby installation.",det:"André Leblanc (COO) received quote via email. 72hr decision window. If accepted, stone order required within 5 days. Robot capacity: KUKA Gamma available from March 10.",s:"Sales",sev:"info",owner:"Sales"},
          {id:"M6",t:"Yesterday 12:30",ty:"milestone",m:"Design file approved: PRJ-019 (Vornado Granite Capitals) — v2.0 signed off.",det:"Robert Ashby (Selldorf) confirmed v2.0 approval via email. Modernist cap profile locked. File exported to PowerMill queue. Toolpath generation scheduled for Feb 21.",s:"Design",sev:"info",owner:"Design"},
          {id:"M7",t:"Yesterday 10:00",ty:"milestone",m:"PRJ-001 RAMSA columns — roughing complete on panels 9–12. Detail pass tomorrow.",det:"KUKA Alpha completed roughing passes 9–12. 12 of 24 panels fully roughed. Detail pass 4mm ball-nose starts Feb 20 AM. On schedule for June delivery.",s:"Fabrication",sev:"info",owner:"Production"},
          {id:"M8",t:"Feb 18, 16:00",ty:"milestone",m:"Client sign-off received: PRJ-003 (NEH National Garden) — design concept A selected.",det:"David Osei (NEH) confirmed Concept A via letter. Artist: Vinnie Bagwell. Maquette approved pending committee ratification March 1. Stone type confirmed: Carrara White CD.",s:"Project Management",sev:"info",owner:"Micah S."},
          {id:"M9",t:"Feb 18, 11:00",ty:"milestone",m:"PRJ-002 (Benedictine Capitals) — capital #9 roughing started. 9/12 now in progress.",det:"KUKA Alpha shifted to capital #9 after completing #8. Current pass: adaptive rough, 20mm bull-nose. Est. completion: Feb 22. Mane detail identified as high complexity — flagged for extra pencil pass.",s:"Fabrication",sev:"info",owner:"Production"},
          {id:"M10",t:"Feb 17, 14:00",ty:"milestone",m:"Stone delivered: Calacatta Gold BLK-2026-0004 arrived at Greenpoint studio.",det:"2 blocks, 0.16t total. Received and logged. Minor hairline vein flagged on Block A (see alert A11). Block B confirmed clear. Assigned to PRJ-017 (Stripe Logo).",s:"Supply Chain",sev:"info",owner:"Logistics"},
          {id:"M11",t:"Feb 16, 09:30",ty:"milestone",m:"PRJ-006 (RAMSA Facade) — Invoice #1 paid in full. $187,500 received.",det:"Wire cleared. Project now 50% funded. Invoice #2 to be sent on project completion, est. April 2026. Margin on track at 15%.",s:"Finance",sev:"info",owner:"Accounts"},
          {id:"M12",t:"Feb 15, 15:00",ty:"milestone",m:"Toolpath generated & approved: PRJ-019 (Vornado Granite Capitals) — 5 passes, 96h est.",det:"PowerMill 2025 generated adaptive rough → precision finish toolpath. Collision simulation passed. Robot code exported and queued for KUKA Delta. Deployment pending stone delivery (ETA March 20).",s:"Toolpath",sev:"info",owner:"Production"},
          {id:"M13",t:"Feb 14, 13:00",ty:"milestone",m:"PRJ-005 (Arsham Eroded Venus) — client progress photos approved. Polish phase confirmed.",det:"Kiona Thunderbird approved 22 progress photos. Artist signed off on surface treatment direction: selective polish vs. raw contrast. HITL phase continues with Carver C2.",s:"HITL Polish",sev:"info",owner:"C2"},
          {id:"M14",t:"Feb 13, 10:00",ty:"milestone",m:"New project created: PRJ-020 (Museum Pedestal) — scoping phase started.",det:"Private collector commission. Turkish White marble, 0.4×0.4×1.2m pedestal. Complexity: medium. Est. value: $28k. Design source: client CAD file. Assigned to Bryan K. for estimation.",s:"Project Management",sev:"info",owner:"Bryan K."},
          {id:"M15",t:"Feb 12, 16:00",ty:"milestone",m:"PRJ-018 (Lion Pair) — 3D scan complete. ZBrush model v2.0 delivered.",det:"Artec 3D scan of clay maquette complete. ZBrush retopo by studio contractor. Symmetrical pair confirmed. File: OBJ 142MB. Approved for toolpath generation pending stone confirmation.",s:"Design",sev:"info",owner:"Design"},
          {id:"M16",t:"Feb 11, 11:00",ty:"milestone",m:"Annual robot maintenance complete: KUKA Beta & KUKA Gamma — full service logged.",det:"6-month service performed by Fanuc-certified tech (Marco R.). Spindles replaced, calibration within 0.05mm. Both robots cleared for heavy workloads. Next service: August 2026.",s:"Equipment",sev:"info",owner:"Shop Floor"},
          {id:"M17",t:"Feb 10, 14:30",ty:"milestone",m:"Website RFQ form live — 3 new leads received within 48 hours.",det:"New contact form with material selector and budget range went live Feb 8. Leads: (1) Schwarz Architects $420k, (2) private residential $32k, (3) hospitality lobby TBD. All routed to estimation agent.",s:"Business Dev",sev:"info",owner:"Sales"},
          {id:"M18",t:"Feb 8, 09:00",ty:"milestone",m:"PRJ-001 RAMSA — panel #4 installed on site. Client confirmed fit.",det:"James Whitfield confirmed panel #4 installed without issue at site visit. Fit within 1mm spec. Client noted 'exceptional' surface quality. Positive signal for Phase 2 commission.",s:"Delivery",sev:"info",owner:"Install Team"},
        ];
        return (
        <div style={{flex:1,overflowY:"auto",padding:"14px 20px"}}>
          <div style={{display:"flex",justifyContent:"flex-end",alignItems:"center",marginBottom:14}}>
              <button onClick={()=>setShowResolved(!showResolved)} style={{display:"flex",alignItems:"center",gap:6,padding:"5px 12px",borderRadius:6,border:showResolved?"1px solid rgba(196,168,130,.3)":"1px solid rgba(255,255,255,.08)",background:showResolved?"rgba(196,168,130,.08)":"transparent",color:showResolved?G:"#706b63",fontSize:11,cursor:"pointer",fontFamily:S,fontWeight:showResolved?600:400}}>
                <span style={{width:14,height:14,borderRadius:4,border:showResolved?"1px solid "+G:"1px solid rgba(255,255,255,.15)",background:showResolved?G+"20":"transparent",display:"flex",alignItems:"center",justifyContent:"center",fontSize:9,color:G}}>{showResolved?"✓":""}</span>
                Show resolved
              </button>
          </div>
          {ALERTS.filter(s=>alertFilt==="All"||(alertFilt==="Alerts"&&s.ty==="alert")||(alertFilt==="Decisions"&&s.ty==="decision")||(alertFilt==="Milestones"&&s.ty==="milestone")||(alertFilt==="Finance"&&s.ty==="finance")||(alertFilt==="Supply"&&s.ty==="supply")||(alertFilt==="Hardware"&&(s.s==="Fabrication"||s.s==="Equipment"||s.m.toLowerCase().includes("robot")||s.m.toLowerCase().includes("bit")||s.m.toLowerCase().includes("spindle")||s.m.toLowerCase().includes("kuka")||s.m.toLowerCase().includes("cnc"))))
          .filter(s=>!alertSearch||s.m.toLowerCase().includes(alertSearch.toLowerCase())||s.s.toLowerCase().includes(alertSearch.toLowerCase())||s.det.toLowerCase().includes(alertSearch.toLowerCase())||(s.owner||"").toLowerCase().includes(alertSearch.toLowerCase()))
          .filter(s=>showResolved||!alertLog[s.id]?.resolved)
          .map(s=>{
            const isExp=expAlert===s.id;
            const resolved=alertLog[s.id]?.resolved;
            const flagged=alertLog[s.id]?.flagged;
            return (
              <div key={s.id} style={{marginBottom:5,borderRadius:6,background:resolved?"rgba(34,197,94,.03)":s.a?"rgba(249,115,22,.04)":s.sev==="high"?"rgba(239,68,68,.03)":CB,border:resolved?"1px solid rgba(34,197,94,.1)":s.a?"1px solid rgba(249,115,22,.12)":s.sev==="high"?"1px solid rgba(239,68,68,.08)":BD,overflow:"hidden",opacity:resolved?.6:1}}>
                <div style={{padding:"12px 14px",display:"flex",gap:10,cursor:"pointer"}} onClick={()=>setExpAlert(isExp?null:s.id)}>
                  <span style={{fontSize:18,color:resolved?"#22c55e":({alert:"#ef4444",milestone:"#22c55e",finance:"#a78bfa",supply:"#f59e0b",decision:"#f59e0b"})[s.ty],flexShrink:0,marginTop:2}}>{resolved?"✓":({alert:"⚠",milestone:"◆",finance:"$",supply:"◫",decision:"⏳"})[s.ty]}</span>
                  <div style={{flex:1}}>
                    <div style={{fontSize:14,color:resolved?"#706b63":"#e2e0dc",lineHeight:1.5,textDecoration:resolved?"line-through":"none"}}>{s.m}</div>
                    <div style={{fontSize:14,color:"#706b63",fontFamily:M,marginTop:3}}>{s.s} · {s.t} · {s.owner}</div>
                  </div>
                  <div style={{display:"flex",flexDirection:"column",gap:4,alignItems:"flex-end",flexShrink:0}}>
                    {resolved&&<Badge c="#22c55e">RESOLVED</Badge>}
                    {flagged&&!resolved&&<Badge c="#f59e0b">FLAGGED</Badge>}
                    {!resolved&&s.a&&<Badge c="#f59e0b">ACTION REQUIRED</Badge>}
                    {!resolved&&s.sev==="high"&&!s.a&&<Badge c="#ef4444">HIGH</Badge>}
                    {!resolved&&s.sev==="medium"&&!flagged&&<Badge c="#f59e0b">MEDIUM</Badge>}
                    <span style={{fontSize:14,color:"#4a4540"}}>{isExp?"▲":"▼"}</span>
                  </div>
                </div>
                {isExp&&<div style={{padding:"0 14px 14px",borderTop:"1px solid rgba(255,255,255,.04)"}}>
                  <div style={{fontSize:14,color:"#a09a92",lineHeight:1.6,background:"rgba(255,255,255,.01)",borderRadius:4,margin:"8px 0",padding:"8px 12px"}}>{s.det}</div>
                  <div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:8}}>
                    <Btn small color="#60a5fa" primary={alertLog[s.id]?.showEmail} onClick={()=>setAlertLog(l=>({...l,[s.id]:{...l[s.id],showEmail:!l[s.id]?.showEmail,showAgent:false}}))}> 📧 Email To</Btn>
                    <Btn small color="#a78bfa" primary={alertLog[s.id]?.showAgent} onClick={()=>setAlertLog(l=>({...l,[s.id]:{...l[s.id],showAgent:!l[s.id]?.showAgent,showEmail:false}}))}> 🤖 Give to Agent</Btn>
                    {!resolved?<Btn small color="#22c55e" onClick={()=>setAlertLog(l=>({...l,[s.id]:{...l[s.id],resolved:true,log:[...(l[s.id]?.log||[]),{t:ts(),m:"Marked as resolved",u:"Current User"}]}}))}> ✓ Mark Resolved</Btn>
                    :<Btn small color="#f59e0b" onClick={()=>setAlertLog(l=>({...l,[s.id]:{...l[s.id],resolved:false,log:[...(l[s.id]?.log||[]),{t:ts(),m:"Reopened — marked unresolved",u:"Current User"}]}}))}> ↩ Mark Unresolved</Btn>}
                    {!flagged?<Btn small onClick={()=>setAlertLog(l=>({...l,[s.id]:{...l[s.id],flagged:true,log:[...(l[s.id]?.log||[]),{t:ts(),m:"Flagged for review",u:"Current User"}]}}))}> 🔖 Flag</Btn>
                    :<Btn small color="#f59e0b" onClick={()=>setAlertLog(l=>({...l,[s.id]:{...l[s.id],flagged:false,log:[...(l[s.id]?.log||[]),{t:ts(),m:"Unflagged",u:"Current User"}]}}))}> 🔖 Unflag</Btn>}
                  </div>
                  {/* Email inline form */}
                  {alertLog[s.id]?.showEmail&&<div style={{padding:10,borderRadius:6,background:"rgba(96,165,250,.04)",border:"1px solid rgba(96,165,250,.1)",marginBottom:8}} className="fu">
                    <div style={{fontSize:14,fontWeight:600,color:"#60a5fa",marginBottom:4}}>Email To</div>
                    <div style={{display:"flex",alignItems:"center",gap:0,marginBottom:6}}>
                      <input value={alertLog[s.id]?.emailAddr||""} onChange={e=>setAlertLog(l=>({...l,[s.id]:{...l[s.id],emailAddr:e.target.value}}))} placeholder="name" style={{flex:1,fontSize:14,borderRadius:"4px 0 0 4px"}}/>
                      <span style={{fontSize:14,color:"#706b63",background:"rgba(255,255,255,.04)",border:"1px solid rgba(255,255,255,.07)",borderLeft:"none",padding:"5px 6px",borderRadius:"0 4px 4px 0",fontFamily:M,whiteSpace:"nowrap"}}>@monumentallabs.co</span>
                    </div>
                    <Btn small primary color="#60a5fa" onClick={()=>{const addr=alertLog[s.id]?.emailAddr;if(addr){setAlertLog(l=>({...l,[s.id]:{...l[s.id],showEmail:false,emailAddr:"",log:[...(l[s.id]?.log||[]),{t:ts(),m:`Emailed to ${addr}@monumentallabs.co`,u:"Current User"}]}}));}}}>Send</Btn>
                  </div>}
                  {/* Agent context form */}
                  {alertLog[s.id]?.showAgent&&<div style={{padding:10,borderRadius:6,background:"rgba(167,139,250,.04)",border:"1px solid rgba(167,139,250,.1)",marginBottom:8}} className="fu">
                    <div style={{fontSize:14,fontWeight:600,color:"#a78bfa",marginBottom:4}}>Context for Agent</div>
                    <textarea value={alertLog[s.id]?.agentCtx||""} onChange={e=>setAlertLog(l=>({...l,[s.id]:{...l[s.id],agentCtx:e.target.value}}))} placeholder="Provide context or instructions for the agent to follow up on this alert..." rows={2} style={{width:"100%",fontFamily:M,fontSize:14,background:"rgba(255,255,255,.04)",border:"1px solid rgba(255,255,255,.07)",color:"#e2e0dc",padding:"6px 10px",borderRadius:4,resize:"vertical",marginBottom:6}}/>
                    <Btn small primary color="#a78bfa" onClick={()=>{const ctx=alertLog[s.id]?.agentCtx;if(ctx){setAlertLog(l=>({...l,[s.id]:{...l[s.id],showAgent:false,agentCtx:"",log:[...(l[s.id]?.log||[]),{t:ts(),m:`Agent assigned: "${ctx.slice(0,80)}${ctx.length>80?"...":""}"`,u:"Current User"}]}}));}}}>Send to Agent</Btn>
                  </div>}
                  {(alertLog[s.id]?.log||[]).length>0&&<div>
                    <div style={{fontSize:14,color:"#706b63",fontWeight:600,textTransform:"uppercase",marginBottom:4}}>Activity Log</div>
                    {(alertLog[s.id]?.log||[]).map((l,li)=><div key={li} style={{fontSize:14,color:"#a09a92",padding:"3px 0",borderBottom:"1px solid rgba(255,255,255,.02)"}}><span style={{color:"#706b63",fontFamily:M,marginRight:4}}>{l.t}</span>{l.m} <span style={{color:"#4a4540"}}>({l.u})</span></div>)}
                  </div>}
                </div>}
              </div>
            );
          })}
        </div>);
      })()}

      {/* ═══ SALES PIPELINE ═══ */}
  </>);
}
