import React from "react";

export default function MCPanelView({ ctx }) {
  const {
    view,
    setViewRaw,
    prjs,
    setPrjs,
    selId,
    setSelIdRaw,
    expS,
    setExpS,
    showNew,
    setShowNew,
    prjSearch,
    setPrjSearch,
    priFilt,
    setPriFilt,
    newP,
    setNewP,
    clk,
    setClk,
    stF,
    setStF,
    stS,
    setStS,
    stD,
    setStD,
    editing,
    setEditing,
    editSnap,
    setEditSnap,
    salesTab,
    setSalesTab,
    estView,
    setEstView,
    estStoneId,
    setEstStoneId,
    estDims,
    setEstDims,
    estCx,
    setEstCx,
    estQty,
    setEstQty,
    estQ,
    setEstQ,
    expEst,
    setExpEst,
    estSearch,
    setEstSearch,
    quoteFilter,
    setQuoteFilter,
    quoteSortBy,
    setQuoteSortBy,
    expAlert,
    setExpAlert,
    alertLog,
    setAlertLog,
    orderModal,
    setOrderModal,
    orderPrj,
    setOrderPrj,
    orderQty,
    setOrderQty,
    orderDims,
    setOrderDims,
    orderNotes,
    setOrderNotes,
    rfqModal,
    setRfqModal,
    rfqPrj,
    setRfqPrj,
    rfqQty,
    setRfqQty,
    rfqDims,
    setRfqDims,
    rfqNotes,
    setRfqNotes,
    rfqTimeline,
    setRfqTimeline,
    rfqEditId,
    setRfqEditId,
    rfqEditNote,
    setRfqEditNote,
    stDbTab,
    setStDbTab,
    orderSearch,
    setOrderSearch,
    editingQuoteId,
    setEditingQuoteId,
    showResolved,
    setShowResolved,
    finAiOpen,
    setFinAiOpen,
    finTab,
    setFinTab,
    mktTab,
    setMktTab,
    robotTab,
    setRobotTab,
    selRobot,
    setSelRobot,
    sc,
    setSc,
    designRecs,
    setDesignRecs,
    sourceRecs,
    setSourceRecs,
    tpGenState,
    setTpGenState,
    tpGenTime,
    setTpGenTime,
    tpProgress,
    setTpProgress,
    tpStatus,
    setTpStatus,
    invDetail,
    setInvDetail,
    invBlocks,
    setInvBlocks,
    allocPrj,
    setAllocPrj,
    cpName,
    setCpName,
    cpEmail,
    setCpEmail,
    cpType,
    setCpType,
    cpDims,
    setCpDims,
    cpStone,
    setCpStone,
    cpBudget,
    setCpBudget,
    cpNotes,
    setCpNotes,
    cpSubmitted,
    setCpSubmitted,
    cpFiles,
    setCpFiles,
    macroTF,
    setMacroTF,
    macroTab,
    setMacroTab,
    macroAI,
    setMacroAI,
    mcPanelOpen,
    setMcPanelOpen,
    mcPanelWidth,
    setMcPanelWidth,
    mcPanelTab,
    setMcPanelTab,
    mcTab,
    setMcTab,
    mcExp,
    setMcExp,
    mcFilt,
    setMcFilt,
    mcDone,
    setMcDone,
    lFilt,
    setLFilt,
    lStatus,
    setLStatus,
    lExp,
    setLExp,
    gSearch,
    setGSearch,
    gSearchOpen,
    setGSearchOpen,
    gSearchFocused,
    setGSearchFocused,
    sideOpen,
    setSideOpen,
    sidebarPinned,
    setSidebarPinned,
    estFiles,
    setEstFiles,
    estAiRefresh,
    setEstAiRefresh,
    stoneDetail,
    setStoneDetail,
    prjRfqLog,
    setPrjRfqLog,
    dbRefreshing,
    setDbRefreshing,
    stDbSearch,
    setStDbSearch,
    alertSearch,
    setAlertSearch,
    estEmailTo,
    setEstEmailTo,
    estClientName,
    setEstClientName,
    estProjectName,
    setEstProjectName,
    estAgentCtx,
    setEstAgentCtx,
    estMargin,
    setEstMargin,
    lossConfirm,
    setLossConfirm,
    quoteApplied,
    setQuoteApplied,
    estShopEmail,
    setEstShopEmail,
    estActionLog,
    setEstActionLog,
    showEstAction,
    setShowEstAction,
    finOverrides,
    setFinOverrides,
    finEditing,
    setFinEditing,
    finScenario,
    setFinScenario,
    finScenarioAdj,
    setFinScenarioAdj,
    alertFilt,
    setAlertFilt,
    leads,
    setLeads,
    selLead,
    setSelLead,
    leadSearch,
    setLeadSearch,
    leadStageFilt,
    setLeadStageFilt,
    pipeQuickFilt,
    setPipeQuickFilt,
    prjTabFilt,
    setPrjTabFilt,
    contactSearch,
    setContactSearch_,
    selContact,
    setSelContact,
    selContactEst,
    setSelContactEst,
    selSupplier,
    setSelSupplier,
    showNewLead,
    setShowNewLead,
    newLead,
    setNewLead,
    capWeek,
    setCapWeek,
    capView,
    setCapView,
    capTab,
    setCapTab,
    capSelSup,
    setCapSelSup,
    capSelClient,
    setCapSelClient,
    tblSort,
    setTblSort,
    capSelPerson,
    setCapSelPerson,
    selDay,
    setSelDay,
    selWeekCF,
    setSelWeekCF,
    cfRange,
    setCfRange,
    revRange,
    setRevRange,
    plRange,
    setPlRange,
    estRobotRate,
    setEstRobotRate,
    estHandRate,
    setEstHandRate,
    estOverhead,
    setEstOverhead,
    estProfit,
    setEstProfit,
    estDist,
    setEstDist,
    estShipFactor,
    setEstShipFactor,
    estQuality,
    setEstQuality,
    newMenuOpen,
    setNewMenuOpen,
    viewTab,
    setViewTab,
    mcOrigin,
    setMcOrigin,
    M,
    S,
    D,
    G,
    CB,
    BD,
    $,
    PC,
    TT,
    PRI,
    STAT_C,
    FC,
    CC,
    ROLES_C,
    stonePrice,
    genInv,
    now,
    ts,
    AsOf,
    STAGES,
    STONE_DB,
    ROBOTS,
    CARVERS,
    INIT_PRJS,
    mkSD,
    INIT_EST_QUEUE,
    EST_STEPS,
    Dot,
    Lbl,
    Badge,
    Btn,
    KPI,
    NAV,
    VIEW_CFG,
    ROUTE_MAP,
    nav,
    finAdj,
    aR,
  } = ctx;

  return (<>

      
      {/* ═══ MISSION CONTROL PANEL ═══ */}
      {mcPanelOpen&&(()=>{
        const ITEMS=[
          // actions
          {kind:"action",sev:"critical",action:"Send unpaid invoice follow-up",
           meta:{Client:"Soho House",Invoice:"INV-2026-0031",Amount:"$21,000",Overdue:"67 days",Contact:"Thomas Aquino",LastContact:"Jan 14"}},
          {kind:"action",sev:"critical",action:"Pull KUKA R6 from queue — inspect spindle bearing",
           meta:{Robot:"KUKA R6",Temp:"94°C",Threshold:"85°C",Bay:"A-2",LastService:"Jan 28"}},
          {kind:"action",sev:"high",action:"Approve Benedictine timeline change",
           meta:{Project:"PRJ-003 Benedictine Abbey",Client:"Erik Bootsma",CurrentDeadline:"May 27",Requested:"April 15",Carver:"Elena R.",Robot:"KUKA Beta"}},
          {kind:"action",sev:"high",action:"Approve Arsham Venus design",
           meta:{Project:"PRJ-007 Arsham Venus",Client:"Stella Arsham",Quote:"$340,000",Designer:"Amir Z.",Robot:"KUKA Alpha",Carver:"Marco V.",SentDate:"Feb 14"}},
          {kind:"action",sev:"high",action:"Order Estremoz White stone — Lion Pair blocked",
           meta:{Project:"PRJ-018 Lion Pair",Client:"NEH",Supplier:"Estremoz Marble Co.",Cost:"$8,400",BlockedSince:"Feb 18"}},
          {kind:"action",sev:"high",action:"Respond to Gensler quote revision request",
           meta:{Project:"Gensler Brooklyn",Client:"Isabelle Morel",Quote:"$280,000",CutRequested:"8% (~$22k)",Deadline:"Feb 22",Owner:"Priya N."}},
          {kind:"action",sev:"medium",action:"Prep Bay A-3 for Carrara delivery",
           meta:{Shipment:"2.1t Bianco Carrara C",Arriving:"Feb 22 8am",Bay:"A-3",Needs:"Forklift + QA team",Project:"PRJ-001"}},
          {kind:"action",sev:"medium",action:"Send Rosewood Hotels quote before deadline",
           meta:{Client:"Andre Leblanc",Value:"$140,000",Deadline:"Feb 21 EOD",Owner:"Priya N."}},
          {kind:"action",sev:"medium",action:"Pre-collect call — Met Cloisters invoice due Mar 10",
           meta:{Invoice:"INV-2026-0052",Client:"Met Cloisters",Amount:"$38,000",Due:"Mar 10",Sent:"Feb 10"}},
          {kind:"action",sev:"low",action:"Follow up with Vornado Realty on quote",
           meta:{Client:"Ben Okafor",Project:"Penn District Lobby",Value:"~$95,000",LastContact:"Feb 14",Owner:"Priya N."}},
          // events
          {kind:"event",sev:"info",action:"KUKA R6 taken offline",
           meta:{Robot:"KUKA R6",Reason:"Spindle temp 94°C",Time:"Today 11:45",Status:"Awaiting inspection"}},
          {kind:"event",sev:"info",action:"Q1 cash flow report published",
           meta:{MTDRevenue:"$312k",AvgRevenue:"$290k",AROutstanding:"$187k",OpenInvoices:"3",Time:"Today 08:30"}},
          {kind:"event",sev:"info",action:"PRJ-001 panels 9–16 roughing complete",
           meta:{Project:"PRJ-001 RAMSA",Operator:"Carlos M.",NextStage:"Detail pass",OnTrack:"Mar 3 delivery",Time:"Feb 20"}},
          {kind:"event",sev:"info",action:"Rosewood Hotels RFQ received",
           meta:{Client:"Andre Leblanc",Value:"$140,000",Window:"Closes Feb 21",Owner:"Priya N.",Time:"Feb 19"}},
          {kind:"event",sev:"info",action:"Amir Z. joined as Design Lead",
           meta:{Focus:"NEH National Garden + PRJ-003 Arsham Venus",StartDate:"Feb 18",Time:"Feb 18"}},
          {kind:"event",sev:"info",action:"Block BLK-2026-0030 placed on QA hold",
           meta:{Block:"BLK-2026-0030",Issue:"Hairline vein near edge",Stone:"Bianco Carrara",Time:"Today 09:15"}},
        ];
        const sevC={critical:"#ef4444",high:"#f59e0b",medium:"#60a5fa",low:"#64748b",info:"#706b63"};
        const sevBg={critical:"rgba(239,68,68,.07)",high:"rgba(245,158,11,.06)",medium:"rgba(96,165,250,.06)",low:"rgba(100,116,139,.05)",info:"rgba(255,255,255,.03)"};
        const sevBorder={critical:"rgba(239,68,68,.2)",high:"rgba(245,158,11,.18)",medium:"rgba(96,165,250,.18)",low:"rgba(100,116,139,.15)",info:"rgba(255,255,255,.07)"};
        const filters=["all","urgent","updates"];
        const visible=mcFilt==="all"?ITEMS.filter((_,i)=>!mcDone.includes(i)):mcFilt==="urgent"?ITEMS.filter((it,i)=>!mcDone.includes(i)&&it.kind==="action"&&(it.sev==="critical"||it.sev==="high")):ITEMS.filter((it,i)=>!mcDone.includes(i)&&(it.kind==="event"||(it.kind==="action"&&it.sev!=="critical"&&it.sev!=="high")));
        return <>
          <div onClick={()=>setMcPanelOpen(false)} style={{position:"fixed",inset:0,zIndex:88}}/>
          <div style={{position:"fixed",top:"50%",left:"50%",transform:"translate(-50%,-50%)",width:"min(900px,96vw)",height:"88vh",background:"#111110",border:"1px solid rgba(255,255,255,.1)",borderRadius:8,display:"flex",flexDirection:"column",zIndex:89,boxShadow:"0 32px 80px rgba(0,0,0,.8)",overflow:"hidden"}}>
            <div style={{padding:"18px 24px 0",flexShrink:0}}>
              <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:16}}>
                <span style={{fontSize:18,fontWeight:700,color:"#e2e0dc",letterSpacing:-.3}}>Mission Control</span>
                <button onClick={()=>setMcPanelOpen(false)} style={{background:"none",border:"none",color:"#4a4540",cursor:"pointer",fontSize:22,lineHeight:1,padding:"0 2px"}}>×</button>
              </div>
              <div style={{display:"flex",gap:5,paddingBottom:14,borderBottom:"1px solid rgba(255,255,255,.06)"}}>
                {filters.map(f=>{
                  const cnt=f==="all"?ITEMS.length:f==="urgent"?ITEMS.filter(i=>i.kind==="action"&&(i.sev==="critical"||i.sev==="high")).length:ITEMS.filter(i=>i.kind==="event"||(i.kind==="action"&&i.sev!=="critical"&&i.sev!=="high")).length;
                  const active=mcFilt===f;
                  const col=f==="urgent"?"#ef4444":f==="updates"?"#60a5fa":"#e2e0dc";
                  const bg=f==="urgent"?"rgba(239,68,68,.07)":f==="updates"?"rgba(96,165,250,.06)":"rgba(255,255,255,.06)";
                  const bdr=f==="urgent"?"rgba(239,68,68,.3)":f==="updates"?"rgba(96,165,250,.25)":"rgba(255,255,255,.2)";
                  return <button key={f} onClick={()=>{setMcFilt(f);setMcExp(null);}} style={{fontSize:12,padding:"4px 13px",borderRadius:20,border:"1px solid "+(active?bdr:"rgba(255,255,255,.07)"),background:active?bg:"transparent",color:active?col:"#4a4540",cursor:"pointer",fontWeight:active?600:400,transition:"all .12s"}}>
                    {f==="all"?"All":f==="urgent"?"Urgent":"Updates"} <span style={{opacity:.5}}>{cnt}</span>
                  </button>;
                })}
              </div>
            </div>
            <div style={{flex:1,overflowY:"auto",padding:"12px 24px 16px",display:"flex",flexDirection:"column",gap:6}}>
              {visible.map((item,vi)=>{
                const i=ITEMS.indexOf(item);
                const isExp=mcExp===i;
                const sc=sevC[item.sev];
                const sb=sevBg[item.sev];
                const sbr=sevBorder[item.sev];
                return <div key={i} onClick={()=>setMcExp(isExp?null:i)}
                  style={{borderRadius:8,background:isExp?sb:"rgba(255,255,255,.02)",border:"1px solid "+(isExp?sbr:"rgba(255,255,255,.05)"),padding:"11px 14px",cursor:"pointer",transition:"background .1s,border .1s"}}>
                  <div style={{display:"flex",alignItems:"center",gap:10}}>
                    <div style={{width:3,alignSelf:"stretch",borderRadius:4,background:sc,flexShrink:0,minHeight:18}}/>
                    <div style={{flex:1,minWidth:0}}>
                      <div style={{fontSize:14,fontWeight:600,color:"#e2e0dc",marginBottom:3}}>{item.action}</div>
                      <div style={{fontSize:12,color:"#4a4540",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>
                        {Object.entries(item.meta).slice(0,4).map(([k,v])=>k+": "+v).join("  ·  ")}
                      </div>
                    </div>
                    <span style={{color:"#3a3530",fontSize:12,flexShrink:0,transition:"transform .15s",display:"inline-block",transform:isExp?"rotate(180deg)":"none"}}>▾</span>
                  </div>
                  {isExp&&<div style={{marginTop:11,paddingTop:11,borderTop:"1px solid rgba(255,255,255,.05)",paddingLeft:13}}>
                    <div style={{display:"flex",flexWrap:"wrap",gap:"10px 28px",marginBottom:14}}>
                      {Object.entries(item.meta).map(([k,v])=><div key={k}>
                        <div style={{fontSize:10,color:"#4a4540",textTransform:"uppercase",letterSpacing:.9,marginBottom:3}}>{k}</div>
                        <div style={{fontSize:12,color:"#a09a92"}}>{v}</div>
                      </div>)}
                    </div>
                    {item.kind==="action"&&<div style={{display:"flex",gap:7}}>
                    </div>}
                  </div>}
                </div>;
              })}
            </div>
          </div>
        </>;
      })()}

      {/* ═══ MARKETING ═══ */}
  </>);
}
